FROM node:22-bookworm-slim

WORKDIR /app

ARG VITE_SUPABASE_URL=https://oasxwsvkpzqwbcmgoigl.supabase.co
ARG VITE_SUPABASE_PUBLISHABLE_KEY=sb_publishable_Gzete2KZs0Lo8xVhwKnQHg_Gm2p_kOi
ARG VITE_SUPABASE_PROJECT_ID=oasxwsvkpzqwbcmgoigl
ARG SUPABASE_SERVICE_ROLE_KEY
ARG RESEND_API_KEY
ARG ANTHROPIC_API_KEY

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV VITE_SUPABASE_PROJECT_ID=$VITE_SUPABASE_PROJECT_ID
ENV SUPABASE_URL=$VITE_SUPABASE_URL
ENV SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV SUPABASE_PROJECT_ID=$VITE_SUPABASE_PROJECT_ID
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY

COPY package.json ./
COPY .npmrc ./

RUN npm install

COPY . .

ENV NODE_ENV=production
ENV PORT=8080

RUN npm run build

EXPOSE 8080

CMD ["npm", "run", "start"]