// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getMissingSupabasePublicEnvVars, getSupabasePublicEnv } from './env';

function createSupabaseClient() {
  const { url, publishableKey } = getSupabasePublicEnv();

  if (!url || !publishableKey) {
    const missing = getMissingSupabasePublicEnvVars({ url, publishableKey });
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Please set them in your environment variables.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(url, publishableKey, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
